[package]
name = "rs-paint"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glib-macros = "0.19.2"
gtk = { version = "0.8.1", package = "gtk4", features = ["v4_12"] }
